export { default as Navbar } from './NavBar/NavBar'
export { default as Footer } from './Footer/Footer'
export { default as Pricing } from './Pricing/Pricing'
export { default as ScrollToTop } from './ScrollToTop/ScrollToTop'
export { default as InfoSection } from './InfoSection/InfoSection'